import type { Globals } from '..';

const reboot: Globals = {
  '*,*::before,*::after': { boxSizing: 'border-box' },
  ':root': { '@media (prefers-reduced-motion: no-preference)': { scrollBehavior: 'smooth' } },
  body: {
    margin: 0,
    fontFamily:
      'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.5,
    color: '#212529',
    backgroundColor: '#fff',
    WebkitTextSizeAdjust: '100%',
    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
  },
  '[tabindex="-1"]:focus:not(:focus-visible)': { outline: '0 !important' },
  hr: {
    margin: '1rem 0',
    color: 'inherit',
    backgroundColor: 'currentColor',
    border: 0,
    opacity: 0.25,
  },
  'hr:not([size])': { height: '1px' },
  'h1, h2, h3, h4, h5, h6': {
    marginTop: 0,
    marginBottom: '0.5rem',
    fontWeight: 500,
    lineHeight: 1.2,
  },
  h1: {
    fontSize: 'calc(1.375rem + 1.5vw)',
    '@media (min-width: 1200px)': {
      fontSize: '2.5rem',
    },
  },
  h2: {
    fontSize: 'calc(1.325rem + 0.9vw)',
    '@media (min-width: 1200px)': {
      fontSize: '2rem',
    },
  },
  h3: {
    fontSize: 'calc(1.3rem + 0.6vw)',
    '@media (min-width: 1200px)': {
      fontSize: '1.75rem',
    },
  },
  h4: {
    fontSize: 'calc(1.275rem + 0.3vw)',
    '@media (min-width: 1200px)': {
      fontSize: '1.5rem',
    },
  },
  h5: { fontSize: '1.25rem' },
  h6: { fontSize: '1rem' },
  p: { marginTop: 0, marginBottom: '1rem' },
  'abbr[title],abbr[data-original-title]': {
    textDecoration: ['underline', 'underline dotted'],
    ['WebkitTextDecoration' as any]: 'underline dotted',
    cursor: 'help',
    ['WebkitTextDecorationSkipInk' as any]: 'none',
    textDecorationSkipInk: 'none',
  },
  address: { marginBottom: '1rem', fontStyle: 'normal', lineHeight: 'inherit' },
  'ol,ul': { paddingLeft: '2rem' },
  'ol,ul,dl': { marginTop: 0, marginBottom: '1rem' },
  'ol ol,ul ul,ol ul,ul ol': { marginBottom: 0 },
  dt: { fontWeight: 700 },
  dd: { marginBottom: '.5rem', marginLeft: 0 },
  blockquote: { margin: '0 0 1rem' },
  'b,strong': { fontWeight: 'bolder' },
  small: { fontSize: '0.875em' },
  mark: { padding: '0.2em', backgroundColor: '#fcf8e3' },
  'sub,sup': {
    position: 'relative',
    fontSize: '0.75em',
    lineHeight: 0,
    verticalAlign: 'baseline',
  },
  sub: { bottom: '-.25em' },
  sup: { top: '-.5em' },
  a: { color: '#0d6efd', textDecoration: 'underline' },
  'a:hover': { color: '#0a58ca' },
  'a:not([href]):not([class]), a:not([href]):not([class]):hover': {
    color: 'inherit',
    textDecoration: 'none',
  },
  'pre,code,kbd,samp': {
    fontFamily: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '1em',
  },
  pre: {
    display: 'block',
    marginTop: 0,
    marginBottom: '1rem',
    overflow: 'auto',
    fontSize: '0.875em',
    msOverflowStyle: 'scrollbar',
  },
  'pre code': { fontSize: 'inherit', color: 'inherit', wordBreak: 'normal' },
  code: { fontSize: '0.875em', color: '#d63384', wordWrap: 'break-word' },
  'a > code': { color: 'inherit' },
  kbd: {
    padding: '0.2rem 0.4rem',
    fontSize: '0.875em',
    color: '#fff',
    backgroundColor: '#212529',
    borderRadius: '0.2rem',
  },
  'kbd kbd': { padding: 0, fontSize: '1em', fontWeight: 700 },
  figure: { margin: '0 0 1rem' },
  'img,svg': { verticalAlign: 'middle' },
  table: { captionSide: 'bottom', borderCollapse: 'collapse' },
  caption: {
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    color: '#6c757d',
    textAlign: 'left',
  },
  th: { textAlign: ['inherit', '-webkit-match-parent' as any] },
  'thead,tbody,tfoot,tr,td,th': {
    borderColor: 'inherit',
    borderStyle: 'solid',
    borderWidth: 0,
  },
  label: { display: 'inline-block' },
  button: { borderRadius: 0 },
  'button:focus': {
    outline: ['1px dotted', '5px auto -webkit-focus-ring-color'],
  },
  'input,button,select,optgroup,textarea': {
    margin: 0,
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 'inherit',
  },
  'button,input': { overflow: 'visible' },
  'button,select': { textTransform: 'none' },
  '[role="button"]': { cursor: 'pointer' },
  select: { wordWrap: 'normal' },
  '[list]::-webkit-calendar-picker-indicator': { display: 'none' },
  'button,[type="button"],[type="reset"],[type="submit"]': {
    WebkitAppearance: 'button',
  },
  'button:not(:disabled),[type="button"]:not(:disabled),[type="reset"]:not(:disabled),[type="submit"]:not(:disabled)': {
    cursor: 'pointer',
  },
  '::-moz-focus-inner': { padding: 0, borderStyle: 'none' },
  textarea: { resize: 'vertical' },
  fieldset: { minWidth: 0, padding: 0, margin: 0, border: 0 },
  legend: {
    float: 'left',
    width: '100%',
    padding: 0,
    marginBottom: '0.5rem',
    fontSize: 'calc(1.275rem + 0.3vw)',
    lineHeight: 'inherit',
    whiteSpace: 'normal',
    '@media (min-width: 1200px)': {
      fontSize: '1.5rem',
    },
  },
  'legend + *': { clear: 'left' },
  '::-webkit-datetime-edit-fields-wrapper,::-webkit-datetime-edit-text,::-webkit-datetime-edit-minute,::-webkit-datetime-edit-hour-field,::-webkit-datetime-edit-day-field,::-webkit-datetime-edit-month-field,::-webkit-datetime-edit-year-field':
    {
      padding: 0,
    },
  '::-webkit-inner-spin-button': { height: 'auto' },
  '[type="search"]': { outlineOffset: '-2px', WebkitAppearance: 'textfield' },
  '::-webkit-search-decoration': { WebkitAppearance: 'none' },
  '::-webkit-color-swatch-wrapper': { padding: 0 },
  '::-webkit-file-upload-button': {
    font: 'inherit',
    WebkitAppearance: 'button',
  },
  output: { display: 'inline-block' },
  iframe: { border: 0 },
  summary: { display: 'list-item', cursor: 'pointer' },
  progress: { verticalAlign: 'baseline' },
  '[hidden]': { display: 'none !important' },
};

export default reboot;
